# Start with FROM cosmtrek/air:v1.43.0 for live relaod
FROM cosmtrek/air:v1.43.0
# Set the working directory to /app
WORKDIR /app

# Copy the source code to the container
COPY . .

# Install the necessary dependencies
RUN go mod download

# Expose the application port
EXPOSE 8080

# Start the live reload server
CMD air
